# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastroCurso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadCurso(object):
    def setupUi(self, cadCurso):
        cadCurso.setObjectName("cadCurso")
        cadCurso.resize(600, 600)
        cadCurso.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.centralwidget = QtWidgets.QWidget(cadCurso)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 81, 16))
        self.label_3.setObjectName("label_3")
        self.entradaNome = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaNome.setGeometry(QtCore.QRect(130, 30, 221, 20))
        self.entradaNome.setObjectName("entradaNome")
        self.entradaCodigo = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaCodigo.setGeometry(QtCore.QRect(130, 80, 221, 20))
        self.entradaCodigo.setObjectName("entradaCodigo")
        self.entradaInst = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaInst.setGeometry(QtCore.QRect(130, 130, 221, 20))
        self.entradaInst.setObjectName("entradaInst")
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setGeometry(QtCore.QRect(50, 190, 75, 23))
        self.btnVoltar.setObjectName("btnVoltar")
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalvar.setGeometry(QtCore.QRect(280, 190, 75, 23))
        self.btnSalvar.setObjectName("btnSalvar")
        self.labelMensagem = QtWidgets.QLabel(self.centralwidget)
        self.labelMensagem.setGeometry(QtCore.QRect(120, 270, 311, 20))
        self.labelMensagem.setText("")
        self.labelMensagem.setObjectName("labelMensagem")
        cadCurso.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(cadCurso)
        self.statusbar.setObjectName("statusbar")
        cadCurso.setStatusBar(self.statusbar)

        self.retranslateUi(cadCurso)
        QtCore.QMetaObject.connectSlotsByName(cadCurso)

    def retranslateUi(self, cadCurso):
        _translate = QtCore.QCoreApplication.translate
        cadCurso.setWindowTitle(_translate("cadCurso", "MainWindow"))
        self.label.setText(_translate("cadCurso", "Nome"))
        self.label_2.setText(_translate("cadCurso", "Código"))
        self.label_3.setText(_translate("cadCurso", "Instituto (CNPJ)"))
        self.btnVoltar.setText(_translate("cadCurso", "Voltar"))
        self.btnSalvar.setText(_translate("cadCurso", "Salvar"))
