# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastroAluno.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadAluno(object):
    def setupUi(self, CadAluno):
        CadAluno.setObjectName("CadAluno")
        CadAluno.resize(613, 526)
        CadAluno.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.centralwidget = QtWidgets.QWidget(CadAluno)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 47, 13))
        self.label_4.setObjectName("label_4")
        self.entradaNome = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaNome.setGeometry(QtCore.QRect(170, 40, 321, 20))
        self.entradaNome.setObjectName("entradaNome")
        self.entradaCpf = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaCpf.setGeometry(QtCore.QRect(170, 80, 321, 20))
        self.entradaCpf.setObjectName("entradaCpf")
        self.entradaNascimento = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaNascimento.setGeometry(QtCore.QRect(170, 120, 321, 20))
        self.entradaNascimento.setObjectName("entradaNascimento")
        self.entradaEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaEmail.setGeometry(QtCore.QRect(170, 160, 321, 20))
        self.entradaEmail.setObjectName("entradaEmail")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 240, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 280, 47, 13))
        self.label_7.setObjectName("label_7")
        self.entradaAnoInicio = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaAnoInicio.setGeometry(QtCore.QRect(170, 200, 321, 20))
        self.entradaAnoInicio.setObjectName("entradaAnoInicio")
        self.entradaCurso = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaCurso.setGeometry(QtCore.QRect(170, 240, 321, 20))
        self.entradaCurso.setObjectName("entradaCurso")
        self.entradaInstituto = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaInstituto.setGeometry(QtCore.QRect(170, 280, 321, 20))
        self.entradaInstituto.setObjectName("entradaInstituto")
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setGeometry(QtCore.QRect(50, 430, 75, 23))
        self.btnVoltar.setObjectName("btnVoltar")
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalvar.setGeometry(QtCore.QRect(270, 430, 75, 23))
        self.btnSalvar.setObjectName("btnSalvar")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 320, 47, 13))
        self.label_8.setObjectName("label_8")
        self.entradaStatus = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaStatus.setGeometry(QtCore.QRect(170, 320, 321, 20))
        self.entradaStatus.setObjectName("entradaStatus")
        self.labelMensagem = QtWidgets.QLabel(self.centralwidget)
        self.labelMensagem.setGeometry(QtCore.QRect(180, 400, 281, 20))
        self.labelMensagem.setText("")
        self.labelMensagem.setObjectName("labelMensagem")
        CadAluno.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CadAluno)
        self.statusbar.setObjectName("statusbar")
        CadAluno.setStatusBar(self.statusbar)

        self.retranslateUi(CadAluno)
        QtCore.QMetaObject.connectSlotsByName(CadAluno)

    def retranslateUi(self, CadAluno):
        _translate = QtCore.QCoreApplication.translate
        CadAluno.setWindowTitle(_translate("CadAluno", "Cadastrar Aluno"))
        self.label.setText(_translate("CadAluno", "Nome"))
        self.label_2.setText(_translate("CadAluno", "CPF"))
        self.label_3.setText(_translate("CadAluno", "Data de nascimento"))
        self.label_4.setText(_translate("CadAluno", "Email"))
        self.label_5.setText(_translate("CadAluno", "Ano de inicio do curso"))
        self.label_6.setText(_translate("CadAluno", "Curso"))
        self.label_7.setText(_translate("CadAluno", "Instituto"))
        self.btnVoltar.setText(_translate("CadAluno", "Voltar"))
        self.btnSalvar.setText(_translate("CadAluno", "Salvar"))
        self.label_8.setText(_translate("CadAluno", "Situação"))
