# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geraCarteirinha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_geraCarteirinha(object):
    def setupUi(self, geraCarteirinha):
        geraCarteirinha.setObjectName("geraCarteirinha")
        geraCarteirinha.resize(600, 600)
        geraCarteirinha.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.centralwidget = QtWidgets.QWidget(geraCarteirinha)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.label.setObjectName("label")
        self.entradaCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaCPF.setGeometry(QtCore.QRect(100, 20, 191, 20))
        self.entradaCPF.setObjectName("entradaCPF")
        self.btnGerar = QtWidgets.QPushButton(self.centralwidget)
        self.btnGerar.setGeometry(QtCore.QRect(140, 100, 75, 23))
        self.btnGerar.setObjectName("btnGerar")
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setGeometry(QtCore.QRect(270, 410, 75, 23))
        self.btnVoltar.setObjectName("btnVoltar")
        self.btnRenovar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRenovar.setGeometry(QtCore.QRect(280, 100, 75, 23))
        self.btnRenovar.setObjectName("btnRenovar")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 160, 461, 191))
        self.widget.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.widget.setObjectName("widget")
        self.labelNome = QtWidgets.QLabel(self.widget)
        self.labelNome.setGeometry(QtCore.QRect(40, 50, 401, 21))
        self.labelNome.setObjectName("labelNome")
        self.labelCurso = QtWidgets.QLabel(self.widget)
        self.labelCurso.setGeometry(QtCore.QRect(40, 100, 221, 16))
        self.labelCurso.setObjectName("labelCurso")
        self.labelAno = QtWidgets.QLabel(self.widget)
        self.labelAno.setGeometry(QtCore.QRect(280, 100, 161, 16))
        self.labelAno.setObjectName("labelAno")
        self.labelCodigo = QtWidgets.QLabel(self.widget)
        self.labelCodigo.setGeometry(QtCore.QRect(40, 150, 221, 16))
        self.labelCodigo.setObjectName("labelCodigo")
        self.labelValidade = QtWidgets.QLabel(self.widget)
        self.labelValidade.setGeometry(QtCore.QRect(280, 150, 161, 16))
        self.labelValidade.setObjectName("labelValidade")
        self.labelInstituto = QtWidgets.QLabel(self.widget)
        self.labelInstituto.setGeometry(QtCore.QRect(110, 10, 231, 31))
        self.labelInstituto.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInstituto.setObjectName("labelInstituto")
        self.labelMensagem = QtWidgets.QLabel(self.centralwidget)
        self.labelMensagem.setGeometry(QtCore.QRect(140, 60, 271, 20))
        self.labelMensagem.setText("")
        self.labelMensagem.setObjectName("labelMensagem")
        self.widget.raise_()
        self.label.raise_()
        self.entradaCPF.raise_()
        self.btnGerar.raise_()
        self.btnVoltar.raise_()
        self.btnRenovar.raise_()
        self.labelMensagem.raise_()
        geraCarteirinha.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(geraCarteirinha)
        self.statusbar.setObjectName("statusbar")
        geraCarteirinha.setStatusBar(self.statusbar)

        self.retranslateUi(geraCarteirinha)
        QtCore.QMetaObject.connectSlotsByName(geraCarteirinha)

    def retranslateUi(self, geraCarteirinha):
        _translate = QtCore.QCoreApplication.translate
        geraCarteirinha.setWindowTitle(_translate("geraCarteirinha", "MainWindow"))
        self.label.setText(_translate("geraCarteirinha", "CPF do aluno:"))
        self.btnGerar.setText(_translate("geraCarteirinha", "Gerar"))
        self.btnVoltar.setText(_translate("geraCarteirinha", "Voltar"))
        self.btnRenovar.setText(_translate("geraCarteirinha", "Renovar"))
        self.labelNome.setText(_translate("geraCarteirinha", "Nome"))
        self.labelCurso.setText(_translate("geraCarteirinha", "Curso"))
        self.labelAno.setText(_translate("geraCarteirinha", "Ano Inicio"))
        self.labelCodigo.setText(_translate("geraCarteirinha", "Codigo Carteirinha"))
        self.labelValidade.setText(_translate("geraCarteirinha", "Validade"))
        self.labelInstituto.setText(_translate("geraCarteirinha", "Inst"))
