# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SistemaCarteirinha(object):
    def setupUi(self, SistemaCarteirinha):
        SistemaCarteirinha.setObjectName("SistemaCarteirinha")
        SistemaCarteirinha.resize(550, 493)
        SistemaCarteirinha.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"")
        self.centralwidget = QtWidgets.QWidget(SistemaCarteirinha)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 100, 222, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnCadastoInsti = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastoInsti.setGeometry(QtCore.QRect(20, 20, 181, 23))
        self.btnCadastoInsti.setObjectName("btnCadastoInsti")
        self.btnCadastroAluno = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastroAluno.setGeometry(QtCore.QRect(20, 60, 181, 23))
        self.btnCadastroAluno.setObjectName("btnCadastroAluno")
        self.btnListInsti = QtWidgets.QPushButton(self.centralwidget)
        self.btnListInsti.setGeometry(QtCore.QRect(20, 140, 181, 23))
        self.btnListInsti.setObjectName("btnListInsti")
        self.btnListAluno = QtWidgets.QPushButton(self.centralwidget)
        self.btnListAluno.setGeometry(QtCore.QRect(20, 180, 181, 23))
        self.btnListAluno.setObjectName("btnListAluno")
        self.btnListCarteirinhas = QtWidgets.QPushButton(self.centralwidget)
        self.btnListCarteirinhas.setGeometry(QtCore.QRect(20, 300, 181, 23))
        self.btnListCarteirinhas.setObjectName("btnListCarteirinhas")
        self.btnGerarCarteirinha = QtWidgets.QPushButton(self.centralwidget)
        self.btnGerarCarteirinha.setGeometry(QtCore.QRect(20, 260, 181, 23))
        self.btnGerarCarteirinha.setObjectName("btnGerarCarteirinha")
        self.btnConsultarCarteirinha = QtWidgets.QPushButton(self.centralwidget)
        self.btnConsultarCarteirinha.setGeometry(QtCore.QRect(20, 340, 181, 23))
        self.btnConsultarCarteirinha.setObjectName("btnConsultarCarteirinha")
        self.cadastrarCurso = QtWidgets.QPushButton(self.centralwidget)
        self.cadastrarCurso.setGeometry(QtCore.QRect(20, 100, 181, 23))
        self.cadastrarCurso.setObjectName("cadastrarCurso")
        self.btnListCursos = QtWidgets.QPushButton(self.centralwidget)
        self.btnListCursos.setGeometry(QtCore.QRect(20, 220, 181, 23))
        self.btnListCursos.setObjectName("btnListCursos")
        SistemaCarteirinha.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SistemaCarteirinha)
        self.statusbar.setObjectName("statusbar")
        SistemaCarteirinha.setStatusBar(self.statusbar)

        self.retranslateUi(SistemaCarteirinha)
        QtCore.QMetaObject.connectSlotsByName(SistemaCarteirinha)

    def retranslateUi(self, SistemaCarteirinha):
        _translate = QtCore.QCoreApplication.translate
        SistemaCarteirinha.setWindowTitle(_translate("SistemaCarteirinha", "Sistema Gerador de Carteirinhas"))
        self.label.setText(_translate("SistemaCarteirinha", "Bem Vindo ao Sistema Gerador de Carteirinhas"))
        self.btnCadastoInsti.setText(_translate("SistemaCarteirinha", "Cadastrar Instituto"))
        self.btnCadastroAluno.setText(_translate("SistemaCarteirinha", "Cadastrar Aluno"))
        self.btnListInsti.setText(_translate("SistemaCarteirinha", "Listar Institutos"))
        self.btnListAluno.setText(_translate("SistemaCarteirinha", "Listar Alunos"))
        self.btnListCarteirinhas.setText(_translate("SistemaCarteirinha", "Listar Carteirinhas Geradas"))
        self.btnGerarCarteirinha.setText(_translate("SistemaCarteirinha", "Gerar Nova Carteirinha"))
        self.btnConsultarCarteirinha.setText(_translate("SistemaCarteirinha", "Consultar Carteirinha Gerada"))
        self.cadastrarCurso.setText(_translate("SistemaCarteirinha", "Cadastrar Curso"))
        self.btnListCursos.setText(_translate("SistemaCarteirinha", "Listar Cursos"))
