# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listaCarteirinha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_listaCarteirinhas(object):
    def setupUi(self, listaCarteirinhas):
        listaCarteirinhas.setObjectName("listaCarteirinhas")
        listaCarteirinhas.resize(600, 600)
        listaCarteirinhas.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.centralwidget = QtWidgets.QWidget(listaCarteirinhas)
        self.centralwidget.setObjectName("centralwidget")
        self.tabelaCarteirinha = QtWidgets.QTableWidget(self.centralwidget)
        self.tabelaCarteirinha.setGeometry(QtCore.QRect(10, 10, 581, 491))
        self.tabelaCarteirinha.setObjectName("tabelaCarteirinha")
        self.tabelaCarteirinha.setColumnCount(3)
        self.tabelaCarteirinha.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaCarteirinha.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaCarteirinha.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaCarteirinha.setHorizontalHeaderItem(2, item)
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setGeometry(QtCore.QRect(260, 520, 75, 23))
        self.btnVoltar.setObjectName("btnVoltar")
        listaCarteirinhas.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(listaCarteirinhas)
        self.statusbar.setObjectName("statusbar")
        listaCarteirinhas.setStatusBar(self.statusbar)

        self.retranslateUi(listaCarteirinhas)
        QtCore.QMetaObject.connectSlotsByName(listaCarteirinhas)

    def retranslateUi(self, listaCarteirinhas):
        _translate = QtCore.QCoreApplication.translate
        listaCarteirinhas.setWindowTitle(_translate("listaCarteirinhas", "MainWindow"))
        item = self.tabelaCarteirinha.horizontalHeaderItem(0)
        item.setText(_translate("listaCarteirinhas", "New Column"))
        item = self.tabelaCarteirinha.horizontalHeaderItem(1)
        item.setText(_translate("listaCarteirinhas", "CPF Aluno"))
        item = self.tabelaCarteirinha.horizontalHeaderItem(2)
        item.setText(_translate("listaCarteirinhas", "Validade"))
        self.btnVoltar.setText(_translate("listaCarteirinhas", "Voltar"))
