# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listaInstitutos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_listInstituto(object):
    def setupUi(self, listInstituto):
        listInstituto.setObjectName("listInstituto")
        listInstituto.resize(600, 600)
        listInstituto.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.centralwidget = QtWidgets.QWidget(listInstituto)
        self.centralwidget.setObjectName("centralwidget")
        self.tabelaInst = QtWidgets.QTableWidget(self.centralwidget)
        self.tabelaInst.setGeometry(QtCore.QRect(10, 40, 581, 471))
        self.tabelaInst.setObjectName("tabelaInst")
        self.tabelaInst.setColumnCount(4)
        self.tabelaInst.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaInst.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaInst.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaInst.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaInst.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 16))
        self.label.setObjectName("label")
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setGeometry(QtCore.QRect(270, 530, 75, 23))
        self.btnVoltar.setObjectName("btnVoltar")
        listInstituto.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(listInstituto)
        self.statusbar.setObjectName("statusbar")
        listInstituto.setStatusBar(self.statusbar)

        self.retranslateUi(listInstituto)
        QtCore.QMetaObject.connectSlotsByName(listInstituto)

    def retranslateUi(self, listInstituto):
        _translate = QtCore.QCoreApplication.translate
        listInstituto.setWindowTitle(_translate("listInstituto", "MainWindow"))
        item = self.tabelaInst.horizontalHeaderItem(0)
        item.setText(_translate("listInstituto", "Nome"))
        item = self.tabelaInst.horizontalHeaderItem(1)
        item.setText(_translate("listInstituto", "CNPJ"))
        item = self.tabelaInst.horizontalHeaderItem(2)
        item.setText(_translate("listInstituto", "Endreço"))
        item = self.tabelaInst.horizontalHeaderItem(3)
        item.setText(_translate("listInstituto", "Telefone"))
        self.label.setText(_translate("listInstituto", "Lista de Institutos"))
        self.btnVoltar.setText(_translate("listInstituto", "Voltar"))
