# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listaAlunos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_listAlunos(object):
    def setupUi(self, listAlunos):
        listAlunos.setObjectName("listAlunos")
        listAlunos.resize(600, 600)
        listAlunos.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.centralwidget = QtWidgets.QWidget(listAlunos)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.label.setObjectName("label")
        self.tabelaAlunos = QtWidgets.QTableWidget(self.centralwidget)
        self.tabelaAlunos.setGeometry(QtCore.QRect(10, 40, 581, 391))
        self.tabelaAlunos.setObjectName("tabelaAlunos")
        self.tabelaAlunos.setColumnCount(7)
        self.tabelaAlunos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaAlunos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaAlunos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaAlunos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaAlunos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaAlunos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaAlunos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaAlunos.setHorizontalHeaderItem(6, item)
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setGeometry(QtCore.QRect(60, 450, 75, 23))
        self.btnVoltar.setObjectName("btnVoltar")
        self.btnTodos = QtWidgets.QPushButton(self.centralwidget)
        self.btnTodos.setGeometry(QtCore.QRect(190, 450, 75, 23))
        self.btnTodos.setObjectName("btnTodos")
        self.btnGraduados = QtWidgets.QPushButton(self.centralwidget)
        self.btnGraduados.setGeometry(QtCore.QRect(330, 450, 75, 23))
        self.btnGraduados.setObjectName("btnGraduados")
        self.btnGraduandos = QtWidgets.QPushButton(self.centralwidget)
        self.btnGraduandos.setGeometry(QtCore.QRect(470, 450, 75, 23))
        self.btnGraduandos.setObjectName("btnGraduandos")
        listAlunos.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(listAlunos)
        self.statusbar.setObjectName("statusbar")
        listAlunos.setStatusBar(self.statusbar)

        self.retranslateUi(listAlunos)
        QtCore.QMetaObject.connectSlotsByName(listAlunos)

    def retranslateUi(self, listAlunos):
        _translate = QtCore.QCoreApplication.translate
        listAlunos.setWindowTitle(_translate("listAlunos", "MainWindow"))
        self.label.setText(_translate("listAlunos", "Lista de Alunos"))
        item = self.tabelaAlunos.horizontalHeaderItem(0)
        item.setText(_translate("listAlunos", "Nome"))
        item = self.tabelaAlunos.horizontalHeaderItem(1)
        item.setText(_translate("listAlunos", "CPF"))
        item = self.tabelaAlunos.horizontalHeaderItem(2)
        item.setText(_translate("listAlunos", "Data de Nascimento"))
        item = self.tabelaAlunos.horizontalHeaderItem(3)
        item.setText(_translate("listAlunos", "Email"))
        item = self.tabelaAlunos.horizontalHeaderItem(4)
        item.setText(_translate("listAlunos", "Curso"))
        item = self.tabelaAlunos.horizontalHeaderItem(5)
        item.setText(_translate("listAlunos", "Instituto"))
        item = self.tabelaAlunos.horizontalHeaderItem(6)
        item.setText(_translate("listAlunos", "Status"))
        self.btnVoltar.setText(_translate("listAlunos", "Voltar"))
        self.btnTodos.setText(_translate("listAlunos", "Listar Todos"))
        self.btnGraduados.setText(_translate("listAlunos", "Graduados"))
        self.btnGraduandos.setText(_translate("listAlunos", "Graduandos"))
